version: "3.9"
services:
  spring-api:
    build: .
    ports:
      - "8080:8080"
    networks:
      - backend

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - backend

networks:
  backend:
volumes:
  mongodata: